.TH "cli::CallbackArgs" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cli::CallbackArgs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::vector< std::string > & \fBarguments\fP"
.br
.ti -1c
.RI "std::ostream & \fBoutput\fP"
.br
.ti -1c
.RI "std::ostream & \fBerror\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
