.TH "/home/srvenkat/matvec-test/src/Comm.hpp" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/srvenkat/matvec-test/src/Comm.hpp \- Header file for the \fBComm\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shared\&.hpp'\fP
.br
\fC#include 'utils\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComm\fP"
.br
.RI "Class representing communication operations\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBComm\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
