.TH "Comm" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comm \- Class representing communication operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Comm\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComm\fP (MPI_Comm comm, int proc_rows, int proc_cols)"
.br
.RI "Constructor for the \fBComm\fP class\&. "
.ti -1c
.RI "\fBComm\fP (\fBComm\fP &comm)"
.br
.RI "Copy constructor for the \fBComm\fP class\&. "
.ti -1c
.RI "\fB~Comm\fP ()"
.br
.RI "Destructor for the \fBComm\fP class\&. "
.ti -1c
.RI "ncclComm_t \fBget_gpu_row_comm\fP ()"
.br
.RI "Get the NCCL communicator for GPU row communication\&. "
.ti -1c
.RI "ncclComm_t \fBget_gpu_col_comm\fP ()"
.br
.RI "Get the NCCL communicator for GPU column communication\&. "
.ti -1c
.RI "int \fBget_device\fP ()"
.br
.RI "Get the GPU device ID\&. "
.ti -1c
.RI "cudaStream_t \fBget_stream\fP ()"
.br
.RI "Get the CUDA stream\&. "
.ti -1c
.RI "MPI_Comm \fBget_row_comm\fP ()"
.br
.RI "Get the MPI communicator for row communication\&. "
.ti -1c
.RI "MPI_Comm \fBget_col_comm\fP ()"
.br
.RI "Get the MPI communicator for column communication\&. "
.ti -1c
.RI "MPI_Comm \fBget_global_comm\fP ()"
.br
.RI "Get the global MPI communicator\&. "
.ti -1c
.RI "int \fBget_row_color\fP ()"
.br
.RI "Get the color of the current process in the row communicator\&. "
.ti -1c
.RI "int \fBget_col_color\fP ()"
.br
.RI "Get the color of the current process in the column communicator\&. "
.ti -1c
.RI "int \fBget_world_rank\fP ()"
.br
.RI "Get the rank of the current process in the global communicator\&. "
.ti -1c
.RI "int \fBget_world_size\fP ()"
.br
.RI "Get the total number of processes in the global communicator\&. "
.ti -1c
.RI "int \fBget_proc_rows\fP ()"
.br
.RI "Get the number of process rows\&. "
.ti -1c
.RI "int \fBget_proc_cols\fP ()"
.br
.RI "Get the number of process columns\&. "
.ti -1c
.RI "cublasHandle_t \fBget_cublasHandle\fP ()"
.br
.RI "Get the cuBLAS handle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing communication operations\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Comm::Comm (MPI_Comm comm, int proc_rows, int proc_cols)"

.PP
Constructor for the \fBComm\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIcomm\fP The MPI communicator\&. 
.br
\fIproc_rows\fP Number of process rows\&. 
.br
\fIproc_cols\fP Number of process columns\&. 
.RE
.PP

.SS "Comm::Comm (\fBComm\fP & comm)\fC [inline]\fP"

.PP
Copy constructor for the \fBComm\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIcomm\fP The \fBComm\fP object to be copied\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Comm::get_col_color ()\fC [inline]\fP"

.PP
Get the color of the current process in the column communicator\&. 
.PP
\fBReturns\fP
.RS 4
The color of the current process in the column communicator\&. 
.RE
.PP

.SS "MPI_Comm Comm::get_col_comm ()\fC [inline]\fP"

.PP
Get the MPI communicator for column communication\&. 
.PP
\fBReturns\fP
.RS 4
The MPI communicator for column communication\&. 
.RE
.PP

.SS "cublasHandle_t Comm::get_cublasHandle ()\fC [inline]\fP"

.PP
Get the cuBLAS handle\&. 
.PP
\fBReturns\fP
.RS 4
The cuBLAS handle\&. 
.RE
.PP

.SS "int Comm::get_device ()\fC [inline]\fP"

.PP
Get the GPU device ID\&. 
.PP
\fBReturns\fP
.RS 4
The GPU device ID\&. 
.RE
.PP

.SS "MPI_Comm Comm::get_global_comm ()\fC [inline]\fP"

.PP
Get the global MPI communicator\&. 
.PP
\fBReturns\fP
.RS 4
The global MPI communicator\&. 
.RE
.PP

.SS "ncclComm_t Comm::get_gpu_col_comm ()\fC [inline]\fP"

.PP
Get the NCCL communicator for GPU column communication\&. 
.PP
\fBReturns\fP
.RS 4
The NCCL communicator for GPU column communication\&. 
.RE
.PP

.SS "ncclComm_t Comm::get_gpu_row_comm ()\fC [inline]\fP"

.PP
Get the NCCL communicator for GPU row communication\&. 
.PP
\fBReturns\fP
.RS 4
The NCCL communicator for GPU row communication\&. 
.RE
.PP

.SS "int Comm::get_proc_cols ()\fC [inline]\fP"

.PP
Get the number of process columns\&. 
.PP
\fBReturns\fP
.RS 4
The number of process columns\&. 
.RE
.PP

.SS "int Comm::get_proc_rows ()\fC [inline]\fP"

.PP
Get the number of process rows\&. 
.PP
\fBReturns\fP
.RS 4
The number of process rows\&. 
.RE
.PP

.SS "int Comm::get_row_color ()\fC [inline]\fP"

.PP
Get the color of the current process in the row communicator\&. 
.PP
\fBReturns\fP
.RS 4
The color of the current process in the row communicator\&. 
.RE
.PP

.SS "MPI_Comm Comm::get_row_comm ()\fC [inline]\fP"

.PP
Get the MPI communicator for row communication\&. 
.PP
\fBReturns\fP
.RS 4
The MPI communicator for row communication\&. 
.RE
.PP

.SS "cudaStream_t Comm::get_stream ()\fC [inline]\fP"

.PP
Get the CUDA stream\&. 
.PP
\fBReturns\fP
.RS 4
The CUDA stream\&. 
.RE
.PP

.SS "int Comm::get_world_rank ()\fC [inline]\fP"

.PP
Get the rank of the current process in the global communicator\&. 
.PP
\fBReturns\fP
.RS 4
The rank of the current process in the global communicator\&. 
.RE
.PP

.SS "int Comm::get_world_size ()\fC [inline]\fP"

.PP
Get the total number of processes in the global communicator\&. 
.PP
\fBReturns\fP
.RS 4
The total number of processes in the global communicator\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
