.TH "enum_array< E, T, N >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_array< E, T, N >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::array< T, N >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T & \fBoperator[]\fP (E e)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (E e) const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int e)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int e) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
