.TH "/home/srvenkat/matvec-test/src/matvec.hpp" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/srvenkat/matvec-test/src/matvec.hpp \- Header file for the Matvec namespace\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shared\&.hpp'\fP
.br
\fC#include 'utils\&.hpp'\fP
.br
\fC#include <cutranspose\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMatvec::setup\fP (Complex **d_mat_freq, const double *const h_mat, const unsigned int block_size, const unsigned int num_cols, const unsigned int num_rows, cublasHandle_t cublasHandle)"
.br
.RI "Set up the matrix and perform necessary initialization\&. "
.ti -1c
.RI "void \fBMatvec::local_matvec\fP (double *const out_vec, double *const in_vec, const Complex *const d_mat_freq, const unsigned int size, const unsigned int num_cols, const unsigned int num_rows, const bool conjugate, const bool unpad, const unsigned int device, cufftHandle forward_plan, cufftHandle inverse_plan, double *const out_vec_pad, Complex *const in_vec_freq, Complex *const out_vec_freq_tosi, Complex *const in_vec_freq_tosi, Complex *const out_vec_freq, cudaStream_t s, cublasHandle_t cublasHandle)"
.br
.RI "Perform local matrix-vector multiplication\&. "
.ti -1c
.RI "void \fBMatvec::compute_matvec\fP (double *out_vec, double *in_vec, Complex *mat_freq_tosi, const unsigned int block_size, const unsigned int num_cols, const unsigned int num_rows, const bool conjugate, const bool full, const unsigned int device, ncclComm_t nccl_row_comm, ncclComm_t nccl_col_comm, cudaStream_t s, double *const in_vec_pad, cufftHandle forward_plan, cufftHandle inverse_plan, cufftHandle forward_plan_conj, cufftHandle inverse_plan_conj, double *const out_vec_pad, Complex *const in_vec_freq, Complex *const out_vec_freq_tosi, Complex *const in_vec_freq_tosi, Complex *const out_vec_freq, cublasHandle_t cublasHandle, Complex *mat_freq_tosi_other, double *const res_pad)"
.br
.RI "Perform matrix-vector multiplication\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the Matvec namespace\&. 

This file contains the declarations of functions and variables related to the Matvec namespace\&. The Matvec namespace provides functions for matrix-vector operations\&. 
.SH "Function Documentation"
.PP 
.SS "void Matvec::compute_matvec (double * out_vec, double * in_vec, Complex * mat_freq_tosi, const unsigned int block_size, const unsigned int num_cols, const unsigned int num_rows, const bool conjugate, const bool full, const unsigned int device, ncclComm_t nccl_row_comm, ncclComm_t nccl_col_comm, cudaStream_t s, double *const in_vec_pad, cufftHandle forward_plan, cufftHandle inverse_plan, cufftHandle forward_plan_conj, cufftHandle inverse_plan_conj, double *const out_vec_pad, Complex *const in_vec_freq, Complex *const out_vec_freq_tosi, Complex *const in_vec_freq_tosi, Complex *const out_vec_freq, cublasHandle_t cublasHandle, Complex * mat_freq_tosi_other, double *const res_pad)"

.PP
Perform matrix-vector multiplication\&. This function performs matrix-vector multiplication using the provided matrix and vectors\&.
.PP
\fBParameters\fP
.RS 4
\fIout_vec\fP Pointer to the output vector\&. 
.br
\fIin_vec\fP Pointer to the input vector\&. 
.br
\fImat_freq_tosi\fP Pointer to the matrix in frequency domain (transpose of input, scaled)\&. 
.br
\fIblock_size\fP The block size for matrix operations\&. 
.br
\fInum_cols\fP The number of columns in the matrix\&. 
.br
\fInum_rows\fP The number of rows in the matrix\&. 
.br
\fIconjugate\fP Flag indicating whether to perform conjugate multiplication\&. 
.br
\fIfull\fP Flag indicating whether to perform full matrix-vector multiplication\&. 
.br
\fIdevice\fP The device ID\&. 
.br
\fIscale\fP The scaling factor\&. 
.br
\fInccl_row_comm\fP The NCCL communicator for row-wise communication\&. 
.br
\fInccl_col_comm\fP The NCCL communicator for column-wise communication\&. 
.br
\fIs\fP The CUDA stream\&. 
.br
\fIin_vec_pad\fP Pointer to the padded input vector\&. 
.br
\fIforward_plan\fP The forward FFT plan\&. 
.br
\fIinverse_plan\fP The inverse FFT plan\&. 
.br
\fIforward_plan_conj\fP The forward FFT plan for conjugate multiplication\&. 
.br
\fIinverse_plan_conj\fP The inverse FFT plan for conjugate multiplication\&. 
.br
\fIout_vec_pad\fP Pointer to the padded output vector\&. 
.br
\fIin_vec_freq\fP Pointer to the input vector in frequency domain\&. 
.br
\fIout_vec_freq_tosi\fP Pointer to the output vector in frequency domain (transpose of input, scaled)\&. 
.br
\fIin_vec_freq_tosi\fP Pointer to the input vector in frequency domain (transpose of input, scaled)\&. 
.br
\fIout_vec_freq\fP Pointer to the output vector in frequency domain\&. 
.br
\fIcublasHandle\fP The handle for the cuBLAS library\&. 
.br
\fImat_freq_tosi_other\fP Pointer to the matrix in frequency domain (transpose of input, scaled) on other devices\&. 
.br
\fIres_pad\fP Pointer to the padded result vector\&. 
.RE
.PP

.SS "void Matvec::local_matvec (double *const out_vec, double *const in_vec, const Complex *const d_mat_freq, const unsigned int size, const unsigned int num_cols, const unsigned int num_rows, const bool conjugate, const bool unpad, const unsigned int device, cufftHandle forward_plan, cufftHandle inverse_plan, double *const out_vec_pad, Complex *const in_vec_freq, Complex *const out_vec_freq_tosi, Complex *const in_vec_freq_tosi, Complex *const out_vec_freq, cudaStream_t s, cublasHandle_t cublasHandle)"

.PP
Perform local matrix-vector multiplication\&. This function performs local matrix-vector multiplication using the provided matrix and vectors\&.
.PP
\fBParameters\fP
.RS 4
\fIout_vec\fP Pointer to the output vector\&. 
.br
\fIin_vec\fP Pointer to the input vector\&. 
.br
\fId_mat_freq\fP Pointer to the matrix in device memory\&. 
.br
\fIsize\fP The size of the vectors\&. 
.br
\fInum_cols\fP The number of columns in the matrix\&. 
.br
\fInum_rows\fP The number of rows in the matrix\&. 
.br
\fIconjugate\fP Flag indicating whether to perform conjugate multiplication\&. 
.br
\fIunpad\fP Flag indicating whether to unpad the output vector\&. 
.br
\fIdevice\fP The device ID\&. 
.br
\fIforward_plan\fP The forward FFT plan\&. 
.br
\fIinverse_plan\fP The inverse FFT plan\&. 
.br
\fIout_vec_pad\fP Pointer to the padded output vector\&. 
.br
\fIin_vec_freq\fP Pointer to the input vector in frequency domain\&. 
.br
\fIout_vec_freq_tosi\fP Pointer to the output vector in frequency domain (transpose of input, scaled)\&. 
.br
\fIin_vec_freq_tosi\fP Pointer to the input vector in frequency domain (transpose of input, scaled)\&. 
.br
\fIout_vec_freq\fP Pointer to the output vector in frequency domain\&. 
.br
\fIs\fP The CUDA stream\&. 
.br
\fIcublasHandle\fP The handle for the cuBLAS library\&. 
.RE
.PP

.SS "void Matvec::setup (Complex ** d_mat_freq, const double *const h_mat, const unsigned int block_size, const unsigned int num_cols, const unsigned int num_rows, cublasHandle_t cublasHandle)"

.PP
Set up the matrix and perform necessary initialization\&. This function sets up the matrix and performs necessary initialization for matrix-vector operations\&.
.PP
\fBParameters\fP
.RS 4
\fId_mat_freq\fP Pointer to the matrix in device memory\&. 
.br
\fIh_mat\fP Pointer to the matrix in host memory\&. 
.br
\fIblock_size\fP The block size for matrix operations\&. 
.br
\fInum_cols\fP The number of columns in the matrix\&. 
.br
\fInum_rows\fP The number of rows in the matrix\&. 
.br
\fIcublasHandle\fP The handle for the cuBLAS library\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
