.TH "nonstd::optional_lite::detail::storage_t< T >::aligned_storage_t" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::optional_lite::detail::storage_t< T >::aligned_storage_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "align_as_type \fBdata\fP [1+(sizeof(value_type) \- 1)/sizeof(align_as_type)]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
