.TH "nonstd::optional_lite::nullopt_t" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::optional_lite::nullopt_t \- disengaged state tag  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <table\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinit\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "optional_constexpr \fBnullopt_t\fP (\fBinit\fP) optional_noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
disengaged state tag 

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
