.TH "nonstd::optional_lite::detail::alignment_of< T >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::optional_lite::detail::alignment_of< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = alignment_logic<sizeof(alignment_of_hack<T>) - sizeof(T), sizeof(T)>::value }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
