.TH "nonstd::variants::detail::helper< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::helper< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef signed char \fBtype_index_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "typedef \fBvariant_TL16\fP (\fBT0\fP, \fBT1\fP, \fBT2\fP, \fBT3\fP, \fBT4\fP, \fBT5\fP, \fBT6\fP, \fBT7\fP, \fBT8\fP, \fBT9\fP, \fBT10\fP, \fBT11\fP, \fBT12\fP, \fBT13\fP, \fBT14\fP, \fBT15\fP) variant_types"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > static U * \fBas\fP (void *data)"
.br
.ti -1c
.RI "template<class U > static U const * \fBas\fP (void const *data)"
.br
.ti -1c
.RI "static type_index_t \fBto_index_t\fP (std::size_t index)"
.br
.ti -1c
.RI "static void \fBdestroy\fP (type_index_t index, void *data)"
.br
.ti -1c
.RI "static type_index_t \fBcopy_construct\fP (type_index_t const from_index, const void *from_value, void *to_value)"
.br
.ti -1c
.RI "static type_index_t \fBcopy_assign\fP (type_index_t const from_index, const void *from_value, void *to_value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
