.TH "nonstd::variants::detail::VisitorApplicatorImpl< R, VT >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::VisitorApplicatorImpl< R, VT >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Visitor , typename T > static R \fBapply\fP (Visitor const &v, T const &arg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
