.TH "nonstd::variants::detail::TypedVisitorUnwrapper< 2, R, Visitor, T2 >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::TypedVisitorUnwrapper< 2, R, Visitor, T2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypedVisitorUnwrapper\fP (const Visitor &visitor_, \fBT2\fP const &val2_)"
.br
.ti -1c
.RI "template<typename T > R \fBoperator()\fP (const T &val1) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const Visitor & \fBvisitor\fP"
.br
.ti -1c
.RI "\fBT2\fP const  & \fBval2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
