.TH "nonstd::variants::variant< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::variant< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvariant\fP (T0 const &t0)"
.br
.ti -1c
.RI "\fBvariant\fP (T1 const &t1)"
.br
.ti -1c
.RI "\fBvariant\fP (T2 const &t2)"
.br
.ti -1c
.RI "\fBvariant\fP (T3 const &t3)"
.br
.ti -1c
.RI "\fBvariant\fP (T4 const &t4)"
.br
.ti -1c
.RI "\fBvariant\fP (T5 const &t5)"
.br
.ti -1c
.RI "\fBvariant\fP (T6 const &t6)"
.br
.ti -1c
.RI "\fBvariant\fP (T7 const &t7)"
.br
.ti -1c
.RI "\fBvariant\fP (T8 const &t8)"
.br
.ti -1c
.RI "\fBvariant\fP (T9 const &t9)"
.br
.ti -1c
.RI "\fBvariant\fP (T10 const &t10)"
.br
.ti -1c
.RI "\fBvariant\fP (T11 const &t11)"
.br
.ti -1c
.RI "\fBvariant\fP (T12 const &t12)"
.br
.ti -1c
.RI "\fBvariant\fP (T13 const &t13)"
.br
.ti -1c
.RI "\fBvariant\fP (T14 const &t14)"
.br
.ti -1c
.RI "\fBvariant\fP (T15 const &t15)"
.br
.ti -1c
.RI "\fBvariant\fP (\fBvariant\fP const &other)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (\fBvariant\fP const &other)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T0 const &t0)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T1 const &t1)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T2 const &t2)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T3 const &t3)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T4 const &t4)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T5 const &t5)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T6 const &t6)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T7 const &t7)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T8 const &t8)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T9 const &t9)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T10 const &t10)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T11 const &t11)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T12 const &t12)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T13 const &t13)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T14 const &t14)"
.br
.ti -1c
.RI "\fBvariant\fP & \fBoperator=\fP (T15 const &t15)"
.br
.ti -1c
.RI "std::size_t \fBindex\fP () const"
.br
.ti -1c
.RI "bool \fBvalueless_by_exception\fP () const"
.br
.ti -1c
.RI "void \fBswap\fP (\fBvariant\fP &other)"
.br
.ti -1c
.RI "template<class T > T & \fBget\fP ()"
.br
.ti -1c
.RI "template<class T > T const & \fBget\fP () const"
.br
.ti -1c
.RI "template<std::size_t K> \fBvariant_alternative\fP< K, \fBvariant\fP >::type & \fBget\fP ()"
.br
.ti -1c
.RI "template<std::size_t K> \fBvariant_alternative\fP< K, \fBvariant\fP >::type const & \fBget\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > static variant_constexpr std::size_t \fBindex_of\fP () variant_noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
