.TH "nonstd::variants::std17" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::std17 \- type traits C++17:  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
type traits C++17: 
.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
