.TH "nonstd::variants::detail::VisitorUnwrapper< R, Visitor, V2 >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::VisitorUnwrapper< R, Visitor, V2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVisitorUnwrapper\fP (const Visitor &visitor_, const V2 &r_)"
.br
.ti -1c
.RI "template<typename \fBT1\fP > R \fBoperator()\fP (\fBT1\fP const &val1) const"
.br
.ti -1c
.RI "template<typename \fBT1\fP , typename \fBT2\fP > R \fBoperator()\fP (\fBT1\fP const &val1, \fBT2\fP const &val2) const"
.br
.ti -1c
.RI "template<typename \fBT1\fP , typename \fBT2\fP , typename \fBT3\fP > R \fBoperator()\fP (\fBT1\fP const &val1, \fBT2\fP const &val2, \fBT3\fP const &val3) const"
.br
.ti -1c
.RI "template<typename \fBT1\fP , typename \fBT2\fP , typename \fBT3\fP , typename \fBT4\fP > R \fBoperator()\fP (\fBT1\fP const &val1, \fBT2\fP const &val2, \fBT3\fP const &val3, \fBT4\fP const &val4) const"
.br
.ti -1c
.RI "template<typename \fBT1\fP , typename \fBT2\fP , typename \fBT3\fP , typename \fBT4\fP , typename \fBT5\fP > R \fBoperator()\fP (\fBT1\fP const &val1, \fBT2\fP const &val2, \fBT3\fP const &val3, \fBT4\fP const &val4, \fBT5\fP const &val5) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const Visitor & \fBvisitor\fP"
.br
.ti -1c
.RI "const V2 & \fBr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
