.TH "nonstd::variants::detail::VisitorApplicator< R >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::VisitorApplicator< R >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Visitor , typename V1 > static R \fBapply\fP (const Visitor &v, const V1 &arg)"
.br
.ti -1c
.RI "template<size_t Idx, typename Visitor , typename V1 > static R \fBapply_visitor\fP (const Visitor &v, const V1 &arg)"
.br
.ti -1c
.RI "template<typename Visitor , typename V1 , typename V2 > static R \fBapply\fP (const Visitor &v, V1 const &arg1, V2 const &arg2)"
.br
.ti -1c
.RI "template<typename Visitor , typename V1 , typename V2 , typename V3 > static R \fBapply\fP (const Visitor &v, V1 const &arg1, V2 const &arg2, V3 const &arg3)"
.br
.ti -1c
.RI "template<typename Visitor , typename V1 , typename V2 , typename V3 , typename V4 > static R \fBapply\fP (const Visitor &v, V1 const &arg1, V2 const &arg2, V3 const &arg3, V4 const &arg4)"
.br
.ti -1c
.RI "template<typename Visitor , typename V1 , typename V2 , typename V3 , typename V4 , typename V5 > static R \fBapply\fP (const Visitor &v, V1 const &arg1, V2 const &arg2, V3 const &arg3, V4 const &arg4, V5 const &arg5)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
