.TH "nonstd::variants::detail::TX< T >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::TX< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTX\fP< T > \fBoperator+\fP () const"
.br
.ti -1c
.RI "\fBTX\fP< T > \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBTX\fP< T > \fBoperator!\fP () const"
.br
.ti -1c
.RI "\fBTX\fP< T > \fBoperator~\fP () const"
.br
.ti -1c
.RI "\fBTX\fP< T > * \fBoperator&\fP () const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator*\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator/\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator%\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator+\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator\-\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator<<\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator>>\fP (U const &) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (T const &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (T const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator&\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator|\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator^\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator&&\fP (U const &) const"
.br
.ti -1c
.RI "template<class U > \fBTX\fP< T > \fBoperator||\fP (U const &) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
