.TH "nonstd::optional_lite::optional< T >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::optional_lite::optional< T > \- class optional  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <table\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "optional_constexpr \fBoptional\fP (\fBnullopt_t\fP) optional_noexcept"
.br
.ti -1c
.RI "optional_constexpr14 \fBoptional\fP (\fBoptional\fP const &other)"
.br
.ti -1c
.RI "template<typename U > \fBoptional\fP (\fBoptional\fP< U > const &other)"
.br
.ti -1c
.RI "\fBoptional\fP (value_type const &value)"
.br
.ti -1c
.RI "\fBoptional\fP & \fBoperator=\fP (\fBnullopt_t\fP) optional_noexcept"
.br
.ti -1c
.RI "\fBoptional\fP & \fBoperator=\fP (\fBoptional\fP const &other)"
.br
.ti -1c
.RI "template<typename U > \fBoptional\fP & \fBoperator=\fP (U const &value)"
.br
.ti -1c
.RI "template<typename U > \fBoptional\fP & \fBoperator=\fP (\fBoptional\fP< U > const &other)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBoptional\fP &other)"
.br
.ti -1c
.RI "optional_constexpr value_type const * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "optional_constexpr14 value_type * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "optional_constexpr value_type const & \fBoperator*\fP () const optional_ref_qual"
.br
.ti -1c
.RI "optional_constexpr14 value_type & \fBoperator*\fP () optional_ref_qual"
.br
.ti -1c
.RI "optional_constexpr \fBoperator safe_bool\fP () const optional_noexcept"
.br
.ti -1c
.RI "optional_constexpr bool \fBhas_value\fP () const optional_noexcept"
.br
.ti -1c
.RI "optional_constexpr14 value_type const & \fBvalue\fP () const optional_ref_qual"
.br
.ti -1c
.RI "optional_constexpr14 value_type & \fBvalue\fP () optional_ref_qual"
.br
.ti -1c
.RI "template<typename U > optional_constexpr value_type \fBvalue_or\fP (U const &v) const"
.br
.ti -1c
.RI "void \fBreset\fP () optional_noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class nonstd::optional_lite::optional< T >"class optional 

optional access error
.PP
optional 

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
