.TH "nonstd::optional_lite::detail::type_of_size< List, N >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::optional_lite::detail::type_of_size< List, N >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd11::conditional\fP< N==sizeof(typenameList::head), typenameList::head, typenametype_of_size< typenameList::tail, N >::type >::type \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
