.TH "nonstd::variants::detail::type_of_size< nulltype, N >" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nonstd::variants::detail::type_of_size< nulltype, N >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef variant_CONFIG_ALIGN_AS_FALLBACK \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
