.TH "profiler_t" 3 "Tue Aug 13 2024" "Version 0.1.0" "FFTMatvec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
profiler_t \- simple profiler based on Hari's sort_profiler for bssn application\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <profiler\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprofiler_t\fP ()"
.br
.RI "simple profiler based on Hari's sort_profiler for bssn application\&. "
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBsnapreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long double \fBseconds\fP"
.br
.ti -1c
.RI "long long \fBp_flpops\fP"
.br
.ti -1c
.RI "long double \fBsnap\fP"
.br
.ti -1c
.RI "long long \fBnum_calls\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "long double \fB_pri_seconds\fP"
.br
.ti -1c
.RI "long long \fB_pri_p_flpops\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
simple profiler based on Hari's sort_profiler for bssn application\&. 


.PP
\fBAuthor\fP
.RS 4
Milinda Fernando School of Computing, University of Utah 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "profiler_t::profiler_t ()"

.PP
simple profiler based on Hari's sort_profiler for bssn application\&. 
.PP
\fBAuthor\fP
.RS 4
Milinda Fernando School of Computing, University of Utah 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for FFTMatvec from the source code\&.
