site_name: "FFTMatvec Documentation"

repo_url: "https://github.com/s769/FFTMatvec"

theme:
  name: 'material'
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences



plugins:
  - search
  - mkdoxy:
      projects:
        FFTMatvec: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src/ # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "Comm.*pp main.cpp Matrix.*pp matvec.*pp shared.hpp tester.*pp utils.cu utils.hpp Vector.*pp" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories

nav:
  - Getting Started: "getting_started.md"
  - API Reference:
    - "Classes":
        - "Comm": "FFTMatvec/classComm.md"
        - "Matrix": "FFTMatvec/classMatrix.md"
        - "Vector": "FFTMatvec/classVector.md"
    - "Namespaces":
        - "Matvec": "FFTMatvec/namespaceMatvec.md"
        - "Utils": "FFTMatvec/namespaceUtils.md"
        - "Tester": "FFTMatvec/namespaceTester.md"
  - LICENSE: "license.md"

